title: "MapleCTF Writeups"
description: Writeups for 2023 MapleCTF competition hosted by the Maple Bacon team from University of British Columbia!
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
